// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSiIjLx5zK3emdO_wZlVmhc-v4nhs3StI',
    appId: '1:877393119251:android:869fffdee266ede9c617e6',
    messagingSenderId: '877393119251',
    projectId: 'antrian-rumah-sakit-pbl',
    databaseURL: 'https://antrian-rumah-sakit-pbl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'antrian-rumah-sakit-pbl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaoCKa2p8pjouULyzRoHP42brYVYJLK1U',
    appId: '1:877393119251:ios:359091468c75dcf9c617e6',
    messagingSenderId: '877393119251',
    projectId: 'antrian-rumah-sakit-pbl',
    databaseURL: 'https://antrian-rumah-sakit-pbl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'antrian-rumah-sakit-pbl.firebasestorage.app',
    iosBundleId: 'com.example.antreanPoliklinik',
  );
}
